// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALs91hJIIYmDD6vPn3JoqaieJqCKGabvA',
    appId: '1:712218810854:web:bafb88a9d5bbb954049e27',
    messagingSenderId: '712218810854',
    projectId: 'practice-4ba6b',
    authDomain: 'practice-4ba6b.firebaseapp.com',
    storageBucket: 'practice-4ba6b.firebasestorage.app',
    measurementId: 'G-V964PXC4GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWV7DjX_SldZjg8485LFUxEJ0qQokUlY',
    appId: '1:712218810854:android:4f5da42d49dfd0a1049e27',
    messagingSenderId: '712218810854',
    projectId: 'practice-4ba6b',
    storageBucket: 'practice-4ba6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLx2jykPKjrTfuaG_iEiTg1dYcfMW1kuc',
    appId: '1:712218810854:ios:e7e9c185bc6f7c19049e27',
    messagingSenderId: '712218810854',
    projectId: 'practice-4ba6b',
    storageBucket: 'practice-4ba6b.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );
}
